### ISSUE TITLE
missing version of nodejs and yarn ?

### ISSUE THREAD

**Issue by pwof42** [LapisHusky/owopserver#5]
: yarn start
yarn run v1.22.19
warning package.json: No license field
$ node src/index.js
file:///home/bessoux/install/owopserver/src/index.js:25
let config = JSON.parse(await fs.readFile("./config.json"))
                        ^^^^^

SyntaxError: Unexpected reserved word
    at Loader.moduleStrategy (internal/modules/esm/translators.js:133:18)
    at async link (internal/modules/esm/module_job.js:42:21)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
(base)

**Comment by bessouat** [comment]
installing nodejs 18 stopped the error to prompt

**Comment by pwof42** [comment]
resolved by installing nodejs v18
